services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - python-next-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - python-next-network
  auth_service:
    build:
      context: .
      dockerfile: flask-backend/auth_service/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    networks:
      - python-next-network
  user_service:
    build:
      context: .
      dockerfile: flask-backend/user_service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
    networks:
      - python-next-network
  next-frontend:
    build:
      context: .
      dockerfile: next-frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth_service
      - user_service
    networks:
      - python-next-network
networks:
  python-next-network:
    driver: bridge  
