FROM python:3.9-slim

WORKDIR /app

COPY auth_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY auth_service/ .

COPY commom/ ./common

EXPOSE 5000

CMD ["python", "app.py"]
